query_dict = {"Basic ML": "machine learning",
              "Basic ML": "machinelearning",
              "Basic ML": "machne learning",
              "Basic ML": "machne lerning",
              "Basic ML": "machine lerning",
              "Basic ML": "artificial intelligence",
              "Basic ML": "artifical intelligence",
              "Basic ML": "artificialintelligence",
              "Basic ML": "scikit learn",
              "Basic ML": "scikitlearn",
              "Deep Learning": "deep learning",
              "Deep Learning": "neural net",
              "Deep Learning": "neuralnet",
              "Deep Learning": "reinforcement learning",
              "Deep Learning": "convolutional neural",
              "Deep Learning": "tensorflow",
              "Deep Learning": "pytorch",
              "SV": "support vector",
              "SV": "supportvector",
              "Trees": "random forest",
              "Trees": "randomforest",
              "Trees": "decision tree",
              "Trees": "decisiontree",
              "Shrinkage": "lasso regression",
              "Shrinkage": "lassoregression",
              "Shrinkage": "elastic net",
              "Shrinkage": "elasticnet",
              "Shrinkage": "ridge regression",
              "Shrinkage": "ridgeregression",
              "Recognition": "optical character recognition",
              "Recognition": "optimal character recognition",
              "Recognition": "tesseract",
              "Recognition": "facial recognition",
              "Gradient Boost": "gradient boost",
              "Gradient Boost": "xgb",
              "Gradient Boost": "xgboost",
              "Gradient Boost": "lightgbm",
              "Gradient Boost": "catboost",
              "ML Eval": "confusion matrix",
              "ML Eval": "f1 score",
              "ML Eval": "aucroc",
              "ML Eval": "auc roc",
              "ML Eval": "roccurve",
              "ML Eval": "rocc urve",
              "ML Eval": "root mean squared error",
              }
