query_list = ["machine learning",
              "machinelearning",
              "machne learning",
              "machne lerning",
              "machine lerning",
              "artificial intelligence",
              "artifical intelligence",
              "artificialintelligence",
              "neural net",
              "neuralnet",
              "support vector",
              "supportvector",
              "random forest",
              "randomforest",
              "decision tree",
              "decisiontree",
              "reinforcement learning",
              "deep learning",
              "lasso regression",
              "lassoregression",
              "elastic net",
              "elasticnet",
              "ridge regression",
              "ridgeregression",
              "non parametric regression",
              "pattern recognition",
              "confusion matrix",
              "optical character recognition",
              "naive bayes"
              "k nearest neighbours",
              "gradient boost",
              "xgb",
              "xgboost",
              "lightgbm",
              "catboost"
              ]
