query_dict = {"Basic ML": ["machine learning", "machinelearning", "machne learning", "machne lerning",
                           "machine lerning", "artificial intelligence", "artifical intelligence",
                           "artificialintelligence", "scikit learn", "scikitlearn",
                           "statistical learning", "statisticallearning", "statisticallerning", "statistical lerning"],
              "Deep Learning": ["deep learning", "neural net", "neuralnet", "reinforcement learning",
                                "convolutional neural", "tensorflow", "pytorch", "transfer learning"],
              "Support Vector": ["support vector", "supportvector"],
              "Trees": ["random forest", "randomforest", "decision tree", "decisiontree"],
              "Shrinkage": ["lasso regression", "lassoregression", "elastic net", "elasticnet",
                            "ridge regression", "ridgeregression"],
              "Recognition": ["optical character recognition", "optimal character recognition",
                              "tesseract", "facial recognition"],
              "Gradient Boost": ["gradient boost", "xgb", "xgboost", "lightgbm", "catboost"],
              "ML Eval": ["confusion matrix", "f1 score", "aucroc", "auc roc",
                          "roccurve", "rocc urve", "root mean squared error"]
              }
